# @see https://github.com/rccyx/rlyx

default_bump = "patch"
bump_tag_message = "{{version}}"
post_bump_command = ""
changelog_header = "# Changelog"
bump_commit_message = "bump to {{version}}"

[changelog]
enable = false
path   = "CHANGELOG.md"

[context]
enable = true