name: CI

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/base-runner

      - if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        run: just fc

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          just f

          if git diff --quiet; then
            just fc
            exit
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "gh action: auto format"
          git push

          just fc
