name: CI
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/base-runner

      - name: Build release
        run: just b

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: lookas-linux-${{ github.sha }}
          path: target/release/lookas
